version: '3.7'
services:
  activemq:
    build:
      context: ./activemq
      dockerfile: ./Dockerfile
    networks:
            - hotel-network
  mysql-server:
    build:
      context: ./mysql
      dockerfile: ./Dockerfile
    networks:
            - hotel-network
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3308:3306"

  hotel-booking-receiver:
    build:
      context: ./hotel-receiver
      dockerfile: ./Dockerfile
    ports:
        - "8081:8080"
    networks:
      - hotel-network
    links:
      - activemq
    depends_on:
      - app-build

  hotel-booking-app:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    ports:
        - "8083:8080"
    networks:
            - hotel-network
    depends_on:
      - app-build
    links:
      - activemq
      - mysql-server


networks:
  hotel-network:
    external: true